In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [127]:
CHUTES_LADDERS = {1:38, 4:14, 9:31, 16:6, 21:42, 28:84, 36:44,
                  47:26, 49:11, 51:67, 56:53, 62:19, 64:60,
                  71:91, 80:100, 87:24, 93:73, 95:75, 98:78}

In [128]:
imax = 101
P = np.zeros((imax,imax))

for i in range(imax):
    if i < imax-6:
        for j in range(i+1,i+7):
            P[i,j] = 1.0/6.0
    else:
        extra = (i+6)-imax
        for j in range(i,imax):
            if i == j:
                P[i,j] = (1.0+extra)/6.0
            else:
                P[i,j] = 1.0/6.0

print(P)

[[0.         0.16666667 0.16666667 ... 0.         0.         0.        ]
 [0.         0.         0.16666667 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.66666667 0.16666667 0.16666667]
 [0.         0.         0.         ... 0.         0.83333333 0.16666667]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [133]:
p_star = P.copy()
for c in CHUTES_LADDERS:
    for k in range(imax):
        p_star[c][k] = 0.0
    for k in range(imax):
        if not k == (c):
            p_star[k][CHUTES_LADDERS[c]] = P[k][CHUTES_LADDERS[c]]+P[k][c]
    for k in range(imax):
        p_star[k][c] = 0.0
print(p_star)

[[0.         0.         0.16666667 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.83333333 0.16666667]
 [0.         0.         0.         ... 0.         0.         1.        ]]


In [134]:
Q = p_star[:imax-1,:imax-1]
N = np.linalg.inv(np.eye(imax-1)-Q)
ones = np.full(imax-1,1).reshape(-1,1)
print(np.matmul(N,ones)[0])

[39.22512231]
